값에 의한 호출|참조에 의한 호출|객체 참조에 의한 호출
-----------|--------------|------------



In [77]:
def swap_value(x,y):
    temp=x
    x=y
    y=temp
a=[1,2,3,4,5]
swap_value(a[1],a[2])
print(a)

[1, 2, 3, 4, 5]


In [78]:
def swap_offset(offset_x, offset_y):
    temp=a[offset_x]
    a[offset_x]=a[offset_y]
    a[offset_y]=temp
a=[1,2,3,4,5]
swap_offset(1,2)
print(a)

[1, 3, 2, 4, 5]


In [79]:
def swap_reference(list, offset_x, offset_y):
    temp=list[offset_x]
    list[offset_x]=list[offset_y]
    list[offset_y]=temp
a=[1,2,3,4,5]
swap_reference(a,1,2)
print(a)

[1, 3, 2, 4, 5]


함수를 만들어보자
이 함수는 두개의 숫자를 input으로 받으면 작은 수로 큰 수를 나눈 몫과 나머지를 반환하는 함수이다.
반환값은 튜플로 되어있으며 몫, 나머지 순으로 되어있다
단 0으로 나누는 것은 불가하기 때문에 두 수 중에 작은 수가 0이라면 화면에 0은 사용할수없습니다 를 출력하고 종료되어야한다.

In [80]:
def div_num(a,b):  
    if a>b:
        if b==0:
            print('0은 사용할 수 없습니다.')
        else:
            c=a//b
            d=a%b
        return (c,d)
    if a<b:
        if a==0:
            print('0은 사용할 수 없습니다.')
        else:
            e=b//a
            f=b%a
        return (e,f)
    
print(div_num(0,1))

0은 사용할 수 없습니다.


UnboundLocalError: local variable 'e' referenced before assignment

In [ ]:
def div3(a,b):
    if a<b:
        big=b
        small=a
    elif b<=a:
        big=a
        small=b
    else:
        print("정수가 아닙니다.")
    if small==0:
        print("0은 사용할 수 없습니다.")
    elif abs(big)<0 or abs(small)<0:
        ("정수를 입력해주세요.")
    else:
        q=big//small
        r=big%small
        return (q,r)

In [ ]:
div3(1,0)

0은 사용할 수 없습니다.


어떠한 string을 받으면 일정한 단위로 끊어서 화면에 출력하는 함수를 짜보자. 끊는 단위는 따로 정하지 않으면 2로 설정해보자.

In [ ]:
def func(string,unit=2):
    string=input("")
    unit=2
    while len(string):
        a=string[0~3], end=""
        return 

In [ ]:
def func(string, unit=2):
    i=0
    while i<len(string):
        print(string[i:i+unit])
        i+=unit
func("테스트를 위한 문장입니다.")

테스
트를
 위
한 
문장
입니
다.


In [ ]:
def test(*args):
    print(args)
def test(*a):
    print(*a)
test(1,2,3,4,5,6,7,8,9,10)
test([1,2],3)
test([1,2])

1 2 3 4 5 6 7 8 9 10
[1, 2] 3
[1, 2]


In [3]:
def add_all(*inputs): # 오류
    i=0
    for i in range(len(inputs)):
        s += inputs[i]
    return s
add_all([1,2,3,4,5,6,7,8,9,10])

UnboundLocalError: local variable 's' referenced before assignment

In [ ]:
def add_all2(*inputs): # 오류
    return sum(inputs)
add_all2([1,2,3,4,5,6,7,8,9,10])

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [4]:
def add_all3(*args):
    s=0
    for i in args:
        for j in i:
            s+=j
        return s
add_all3([1,2,3,4,5,6,7,8,9,10])

55

In [5]:
def add_all4(*args):
    temp=0
    for i in range(len(args)):
        if type(args[i])==list:
            for j in args[i]:
                temp +=j
        else: temp += args[i]
add_all4([1,2,3,4,5,6,7,8,9,10])
    return temp

IndentationError: unexpected indent (841579918.py, line 9)

In [ ]:
def factorial(n): # 재귀적으로 하지 않은 것
    s=1 # 곱을 계산할 변수의 초깃값
    for i in range(1, n+1): # 1부터 n까지 반복
        s=s*i # 곱셈연산
    return s
factorial(5)

120

In [ ]:
def fact(n): # 재귀적으로 하는 것(함수안에서 돌게만드는것)
    if n<=1: # n이 1 이하이면 종료조건
        return 1 
    return n*fact(n-1)
fact(5)

120

- 참고 : https://velog.io/@joo4438/python-%ED%8C%A9%ED%86%A0%EB%A6%AC%EC%96%BC-%EA%B5%AC%ED%95%98%EA%B8%B0%EC%9E%AC%EA%B7%80

파이썬 심화

In [ ]:
people=["펭수","뽀로로","뚝딱이","텔레토비"]
def func1(line):
    new_lines=[]
    i=1 # 대기번호를 트래킹하는 변수
    for s in line:
        print("대기번호 %d번:%s"%(i,s))
        i+=1 # 별도 업데이트 필요
        new_lines.append((i,s))
    return new_lines
lines=func1(people)

대기번호 1번:펭수
대기번호 2번:뽀로로
대기번호 3번:뚝딱이
대기번호 4번:텔레토비


In [ ]:
people=["펭수","뽀로로","뚝딱이","텔레토비"]
def func2(line):
    new_lines=[]
    for idx,val in enumerate(line):
        print("대기번호 %d번:%s"%(idx,val))
        new_lines.append((idx+1,val))
    return new_lines
lines=func2(people)

대기번호 0번:펭수
대기번호 1번:뽀로로
대기번호 2번:뚝딱이
대기번호 3번:텔레토비


- enumerate(열거하다)
  - 반복 가능한 객체의 인덱스와 원소에 함게 접근할 수 있는 함수
  

In [ ]:
lst=["a","b","c"]
for x in enumerate(lst):
    print(x)
lst1="abcd"
for x in enumerate(lst1):
    print(x)

(0, 'a')
(1, 'b')
(2, 'c')
(0, 'a')
(1, 'b')
(2, 'c')
(3, 'd')


- zip
  - 반복가능한 객체들을(2개이상)병렬적으로 묶어주는 함수
  - 각 원소들을 튜플의 형식으로 묶어줌

In [ ]:
str_list=["one", "two","three","four"]
num_list=[1,2,3,4]
for i in zip(num_list, str_list):
    print(i)

(1, 'one')
(2, 'two')
(3, 'three')
(4, 'four')


- lambda

In [ ]:
def plus_two(num):
    return num+2
a=2
b=plus_two(a)
print(b)


4


In [ ]:
lambda x:x+2
# <function__main__,<lambda>(x)>
# 람다는 함수를 생성함
func2=lambda x :x+2
c=func2(2)
c

4

- map
  - 리스트, 튜플, 스트링 등 자료형 각각의 원소에 동일한 함수를 적용

In [ ]:
items=[1,2,3,4,5]
squared=[]
for i in items:
    squared.append(i*i)
print(squared)

[1, 4, 9, 16, 25]


In [ ]:
squared_map=list(map(lambda x : x**2,items))
print(squared_map)

[1, 4, 9, 16, 25]


In [ ]:
items=[1,24,3,6,7]
str_items=list(map(lambda x:str(x),items))
# items에 있는 값들을 map(각 원소에 동일한 함수 적용)하여
# string으로 변환하여 람다를 이용해 함수를 줄여
# 리스트를 작성한다
print(str_items)

['1', '24', '3', '6', '7']


0~9까지를 순서대로 가지고 있는 리스트를 만드세요

In [ ]:
#1.
list_1=[0,1,2,3,4,5,6,7,8,9]
#2.
list_2=[]
for x in range(10):
    list_2.append(x)
print(list_2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


 for문
 - 구구단 2단을 list comprehension을 이용하여 구현하고 리스트를 화면에 출력해보자
 - 다음의 문장을 분석해보자
 "코로나 바이러스를 예방하기 위해 사회적 거리두기를 실천합시다. 마스크를 끼고 손씻기를 생활화합시다."
 라는 문장을 띄어쓰기 별로 분석하려고 한다. 띄어쓰기별 문장을 나눈 후 각 요소의 길이를 리스트에 저장하라.
 (띄어쓰기는 split 함수를 써라)

In [ ]:
list_3=[2*x for x in range(1,10)]
print(list_3)


[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
sentence="코로나 바이러스를 예방하기 위해 사회적 거리두기를 실천합시다. 마스크를 끼고 손씻기를 생활화합시다."
len_sent=[len(s) for s in sentence.split()]
print(len_sent)

[3, 5, 4, 2, 3, 5, 6, 4, 2, 4, 7]


10부터 20까지의 숫자들 중에서 짝수만을 담은 리스트를 만들어보자

In [ ]:
list_3=[]
for x in range(10,21):
    if x%2==0:
        list_3.append(x)
print(list_3)

lc_2=[x for x in range(10,21) if x%2==0]
print(lc_2)

[10, 12, 14, 16, 18, 20]
[10, 12, 14, 16, 18, 20]


for문+if문
1부터 10의 제곱수 중 50 이하인 수만 리스트에 저장하라

"코로나 바이러스를 예방하기 위해 사회적 거리두기를 실천합시다. 마스크를 끼고 손씻기를 생활화합시다."라는 문장을 띄어쓰기별로 분석하려고 한다. 띄어쓰기별로 문장을 나눈 후 각 요소의 길이가 5미만인 것들을 리스트에저장하라

In [ ]:
li3=[x**2 for x in range(1,11) if x**2>50]
print(li3)

[64, 81, 100]


In [ ]:
li4=[len(s) for s in sentence.split() if len(s)<5]
print(li4)

[3, 4, 2, 3, 4, 2, 4]


for문 + if문
- 1부터 10까지의 숫자들 중 홀수이면 제곱수를, 짝수이면 세제곱수를 담은 리스트를 만들어보자.

In [ ]:
li_4=[]
for x in range(1,11):
    if x%2==1:
        li_4.append(x**2)
    else:
        li_4.append(x**3)
print(li_4)


[1, 8, 9, 64, 25, 216, 49, 512, 81, 1000]


In [ ]:
[x**2 if x%2==1 else x**3 for x in range(1,11)]
# else가 나오면 if문이 앞으로 나옴

[1, 8, 9, 64, 25, 216, 49, 512, 81, 1000]

In [ ]:
word_1="hello"
word_2="world"

result=[i+j for i in word_1 for j in word_2]
result

['hw',
 'ho',
 'hr',
 'hl',
 'hd',
 'ew',
 'eo',
 'er',
 'el',
 'ed',
 'lw',
 'lo',
 'lr',
 'll',
 'ld',
 'lw',
 'lo',
 'lr',
 'll',
 'ld',
 'ow',
 'oo',
 'or',
 'ol',
 'od']

- 40 이하의 숫자는 5를 더하고 40 초과의 숫자는 41로 바꾸어 리스트로 저장하고, 리스트를 출력하라.
- 컷트라인이 60점일때, 사람이름과 통과여부를 리스트로 담아서 출력하라. 이름과 통과여부는 튜플로 묶어있는 자료이다.

In [ ]:
list_5=[12,67,32,48,19,57,29,49]
lc_6=[x+5 if x<=40 else 41 for x in list_5]

In [ ]:

students = {"보라돌이":61, "뚜비":35, "나나":78,"뽀":88}

result = [(name,True) if score>60 else (name, False) for name,score in students.items()]
result

선형수학 행열

numpy

In [ ]:
import numpy as np
n=1000000
numpy_arr=np.arange(n)
python_list=list(range(n))


NameError: name 'time' is not defined

In [ ]:
%%time
#jupy notebook
python_list=[x**3+10 for x in python_list]


CPU times: total: 328 ms
Wall time: 346 ms


In [ ]:
from time import time
python_list = [x**3+10 for x in python_list]
time()

1683010368.5413961

In [ ]:
import time
start=time.time() #시작시간 저장
python_list=[x**3+10 for x in python_list]
print('time:'.time.time()-start)

AttributeError: 'str' object has no attribute 'time'

- 벡터화
  - 배열은 for문을 작성하지 않고 데이터를 일괄처리 하는 것.


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
10-arr

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
arr/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [ ]:
arr*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
arr2=np.array([100,200,300])
arr3=np.array([100,200])

In [ ]:
arr+arr3

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
arr+arr2

array([[101, 202, 303],
       [104, 205, 306]])

In [ ]:
arr4=np.array([[100],[200]])
arr4

array([[100],
       [200]])

In [ ]:
list_1=[1,2,3]
list_1+list_1

[1, 2, 3, 1, 2, 3]

In [ ]:
arr_1=np.array([1,2,3])
arr_1+arr_1

array([2, 4, 6])

- dtype
  - 배열에 담긴 원소의 자료형(ndarray) 같은 자료형을 담음.

In [ ]:
arr.dtype

dtype('int32')

- size
  - 배열에 있는 원소 전체의 갯수

In [ ]:
arr.size

6

- ndim
  - 배열 차원의 갯수

In [ ]:
arr.ndim

2

- shape

In [ ]:
arr.shape # 2행 3열입니다.

(2, 3)

- 0차원(상수)

In [ ]:
import numpy as np
a=np.array(10)
print(a)
print(a.ndim)

10
0


- 1차원

In [ ]:
a=np.array([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


- 2차원

In [ ]:
a=np.array([[1,2],[3,4]])
print(a)
print(a.ndim)

[[1 2]
 [3 4]]
2


- 3차원

In [ ]:
a=np.array([[[1,2],[3,4]]])
print(a)
print(a.ndim)
print(a.shape)

[[[1 2]
  [3 4]]]
3
(1, 2, 2)


- range 함수 이용

In [ ]:
arr1=np.array(range(20))
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2=np.arange(20) # arr1과 똑같으나 훨씬 많이 사용
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.zeros(5) # 0이 할당되어있음

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((4),5)

array([5, 5, 5, 5])

In [ ]:
np.empty((2,3), dtype=np.float32) # 할당된 값이 아님

array([[ 4.146185e+11,  9.795076e-43,  0.000000e+00],
       [ 0.000000e+00,  1.401298e-45, -0.000000e+00]], dtype=float32)

In [ ]:
np.arange(-3,3) # -3부터 2까지

array([-3, -2, -1,  0,  1,  2])

In [ ]:
np.arange(3,50,3) # 3부터 49까지 3칸씩 띄우기

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [ ]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

https://aruie.github.io/2019/06/19/numpy.html

- 배열결합함수
  - hstack, concatenate(axis=0)
  - 두 배열을 왼쪽에서 오른쪽으로 붙이기

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

- vstack, concate

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((a,b),axis=1) # 1D vector는 안됨.

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
c = np.array([[0,1,2],[3,4,5]])
d = np.array([[6,7,8],[9,10,11]])
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [81]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [82]:
np.column_stack([a,b])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [91]:
import random
import numpy as np

In [92]:
random.random() # 0<리턴값<1

0.023871310065874174

In [95]:
data=[1,2,3,4,5,6,7]
np.random.choice(data,3)

array([4, 1, 2])

In [96]:
data=["apple", "banana", "grape", "orange"]
random.choice(data)

'apple'

- seed
  - 난수 초기값 부여-> 재현가능성(reporducibility) 

In [97]:
np.random.seed(42)

In [99]:
np.random.rand(10000) # 난수

array([0.37364082, 0.3329121 , 0.17615391, ..., 0.30369847, 0.44332001,
       0.17226481])

In [100]:
np.random.randn(10000) # 정규분포

array([-0.80380318,  0.58599177,  1.30628048, ...,  1.08810529,
        1.95198643,  0.22164209])

로또번호 생성기를 만드세요

In [139]:
import random
import numpy as np
a=np.arange(1,46,1)
b=int(input("로또번호를 몇개 생성할까요?"))
print("로또번호를 몇 개 생성할까요?>",b)
for i in range(1, b+1):
    print(i,". 로또번호:", np.random.choice(a,6))
    i+=1

로또번호를 몇 개 생성할까요?> 4
1 . 로또번호: [39 34 22 13 36  6]
2 . 로또번호: [17 26 24  9  2 20]
3 . 로또번호: [27  6 27 24 15 33]
4 . 로또번호: [42 10 21  6 30 23]


In [2]:
import numpy as np
def make_lotto(count):
    for i in range(count):
        lotto_num = [] #로또 번호가 담길 리스트형 변수
        for j in range(6): #6번 반복
            lotto_num = np.random.choice(range(1,46),6,replace=False)
            lotto_num.sort() #값 정렬
        print('{}.로또번호:{}'.format(i+1,lotto_num))

ModuleNotFoundError: No module named 'numpy'

In [143]:
count = int(input('로또 번호를 몇개 생성할까요?'))
make_lotto(count)

1.로또번호:[ 7 13 15 23 40 43]
2.로또번호:[ 5 14 16 20 29 41]
3.로또번호:[33 35 37 40 42 43]
4.로또번호:[ 7  9 17 22 36 43]


https://colab.research.google.com/drive/1ui5VjU3VbQ0D6SbgruuEm759wqgNFdWN?usp=sharing#scrollTo=5whLRXDxryC2
https://github.com/Youngpyoryu/Lecture_Note/tree/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC