In [8]:
def add_all(*args):
    s=0
    for i in range(len(args)):
        s+=args[i]
    return s
add_all([1,2,3,4,5,6,7,8,9,10])

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

In [ ]:
def add_all3(*args):
    s=0
    for i in args:
        for j in i:
            s+=j
    return s
add_all3([1,2,3,4,5,6,7,8,9,10])

55

In [ ]:
def add_all4(*args):
    temp=0
    for i in range(len(args)):
        if type(args[i])==list:
            for i in args[i]:
                temp +=i
        else:
            temp+=args[i]
    return temp

In [ ]:
add_all4([1,2,3,4,5,6,7,8,9,10])

55

In [1]:
import numpy as np
A=[1,2,3,4]
a=np.array(A)
s=a[:2]
print('A의 출력입니다.%a'%a) # 복사하면 리스트(값만 복사되므로)
print('s의 출력입니다.%s'%s)

A의 출력입니다.array([1, 2, 3, 4])
s의 출력입니다.[1 2]


In [2]:
a1=np.asarray(A)
print(type(a1))
a1

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [ ]:
ss=a[:2].copy()
print(ss.size)
ss[0]=99 # 
print(a)
print(s)
print(ss)

2
[1 2 3 4]
[1 2]
[99  2]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
10-arr

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
arr*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [4]:
arr/3

NameError: name 'arr' is not defined

In [ ]:
arr2=np.array([[100],[200],[300]])

In [ ]:
arr4=np.array([[100],[200],[300]])
arr4

array([[100],
       [200],
       [300]])

In [3]:
arr3=np.array[[100,200]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
arr.flatten() # 1D vector로 만드는 것(1차원의 벡터)

In [ ]:
arr=np.array([[1,2],[3,4]])
arr
arr.flatten()

array([1, 2, 3, 4])

- reshape
  - 이미 존재하는 배열을 내가 원하는대로 shape을 조정함

In [ ]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr.reshape(3,4) # 주어진 shape의 약수로 이루어진 shape만 기능

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.reshape(4,3)
arr.reshape(1,12) # = flatten()
arr.reshape(12,1)
arr.reshape(2,6)
arr.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.reshape(2,-1) # -1값 행이나 열에 넣으면 계산을 하지 않아도 자동으로 축을 만들어줌

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
arr.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
print(arr.transpose().shape) # 행과 열을 바꿔도 기존값은 안바뀜 함수의 리턴차이 체크
arr.transpose()

(5, 4)


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
arr1=np.arange(4).reshape(-1,2)
arr1

array([[0, 1],
       [2, 3]])

In [ ]:
arr1.transpose() # 기존값은 바뀌지않음

array([[0, 2],
       [1, 3]])

In [ ]:
arr1

array([[0, 1],
       [2, 3]])

In [ ]:
arr=np.arange(30).reshape(3,2,5) # 3행 2열이 5판이 있음
arr.shape

(3, 2, 5)

In [ ]:
arr.transpose().shape # 차원이 변경되므로 잘 안씀(넘파이는 2d까지)

(5, 2, 3)

In [ ]:
arr.T

array([[[ 0, 10, 20],
        [ 5, 15, 25]],

       [[ 1, 11, 21],
        [ 6, 16, 26]],

       [[ 2, 12, 22],
        [ 7, 17, 27]],

       [[ 3, 13, 23],
        [ 8, 18, 28]],

       [[ 4, 14, 24],
        [ 9, 19, 29]]])

In [ ]:
x=np.arange(6).reshape(-1,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

- T operation

In [ ]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

- sort와 sorted의 차이
  - 변경이 되느나 얀되느냐
  - 리턴값, 결과값 확인

In [ ]:
A=[5,23,2,1,5] 
A.sort()

In [ ]:
A

[1, 2, 5, 5, 23]

In [ ]:
a1=[5,23,2,1,5]
sorted(a1)

[1, 2, 5, 5, 23]

In [ ]:
a1

[5, 23, 2, 1, 5]

0~20 까지의 숫자를 배열을 만든 후 arr1에는 짝수
arr2에는 홀수가 들어간 배열을 출력해보자.

In [ ]:
import numpy as np

arr=np.arange(0,21)
arr1=[]
arr2=[]
for i in arr:
    if arr[i]%2==0:
        arr1.append(arr[i])
    else:
        arr2.append(arr[i])
print(arr1)
print(arr2)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [ ]:
import numpy as np
arr3=np.arange(0,21)
arr4=arr3[arr3%2==0]
arr5=arr3[arr3%2!=0]
print(arr4)
print(arr5)

[ 0  2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
arr1d=np.arange(5)

In [ ]:
arr1d[1] # 인덱싱 가능

1

In [ ]:
arr1d[-1]

4

In [ ]:
arr1d[:4] # 슬라이싱 가능

array([0, 1, 2, 3])

- 브로드캐스팅

In [ ]:
lst=list(range(6))
lst

[0, 1, 2, 3, 4, 5]

In [ ]:
lst[2:5]=-1 # 리스트에선 슬라이싱 값 변경 불가
lst

TypeError: can only assign an iterable

In [ ]:
lst[3]=-1 # 인덱싱 값 변경 가능
lst

[0, 1, 2, -1, 4, 5]

In [ ]:
arr1d=np.arange(8)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr1d[3:6]=100 # 넘파이에서는 슬라이싱 값 변경 가능
arr1d

array([  0,   1,   2, 100, 100, 100,   6,   7])

- veiw

In [ ]:
arr2d=np.arange(20).reshape(4,-1)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr2d[0] # 0행

array([0, 1, 2, 3, 4])

In [ ]:
arr2d[1][2] # 재귀적 접근 / 1행 2열

7

In [ ]:
arr2d[1,2] # 컴마를 이용하여 쉽게 인덱싱 할 수 있음

7

In [ ]:
arr2d[:3][:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr2d[:3,:2] # 행과 열을 접근하기 위해서는 컴마로 연결

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

- 불리안 배열

In [ ]:
arr=np.array([0,1,2,3,4])
arr[[True,False,True,False,True]] # True인 값들만 나옴

array([0, 2, 4])

In [ ]:
arr2d=np.arange(20).reshape(4,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr2d[[0,2]] # 0행과 2행 # multi index는 []를 하나 더 추가해야함.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [ ]:
arr2d[[0,3],[4]] # 0행과 2행의 4번째 인덱스값 가져옴

array([ 4, 19])

In [ ]:
arr2d[[0,1],[4,3]]

array([4, 8])

In [ ]:
arr2d[[0,1,2],[4,3,1]]

array([ 4,  8, 11])

- 유니버설 함수

In [ ]:
arr=np.arange(-3,3).reshape(3,-1)
arr

array([[-3, -2],
       [-1,  0],
       [ 1,  2]])

In [ ]:
np.exp(arr) # e의 x제곱, 임의의 값의 0제곱은 항상 1

array([[0.04978707, 0.13533528],
       [0.36787944, 1.        ],
       [2.71828183, 7.3890561 ]])

- floor:소수점 버리기

In [ ]:
np.floor(arr)

array([[-3., -2.],
       [-1.,  0.],
       [ 1.,  2.]])

- 이항 유니버설 함수

In [ ]:
arr1=np.arange(8).reshape(2,-1)
arr2=np.arange(-40,40,10).reshape(2,-1)
print(arr1)
print(arr2)

[[0 1 2 3]
 [4 5 6 7]]
[[-40 -30 -20 -10]
 [  0  10  20  30]]


In [ ]:
np.maximum(arr1,arr2) # 같은 원소를 비교하여 가장 큰 값이 나옴

array([[ 0,  1,  2,  3],
       [ 4, 10, 20, 30]])

In [ ]:
np.subtract(arr1,arr2) # 뺄셈

array([[ 40,  31,  22,  13],
       [  4,  -5, -14, -23]])

In [ ]:
np.multiply(arr1,arr2) # 같은 원소끼리 곱셈

array([[  0, -30, -40, -30],
       [  0,  50, 120, 210]])

- 통계 메서드

In [ ]:
arr=np.arange(4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [ ]:
arr.sum() # 모든 요소 더함

6

In [ ]:
arr.sum(axis=0) # 열 계산(컴퓨터는 열 위주)

array([2, 4])

In [ ]:
arr.sum(axis=1) # 행 계산

array([1, 5])

In [ ]:
arr.mean() # 평균

1.5

In [ ]:
arr.mean(axis=0) # 실수형 안에 정수형이 있고, 더 큰 범위 float형으로 나타냄

array([1., 2.])

In [ ]:
arr.mean(axis=1) # 평균 (0+1)/2, (2+3)/2

array([0.5, 2.5])

- where
  - x if 조건 else y의 벡터화 버전
  - numpy를 사용하여 배열을 빠르게 처리할 수 있으며, 다차원도 간결하게 표현이 가능

In [ ]:
xarr=np.array([100,200,300,400])
yarr=np.array([1,2,3,4])
cond=np.array([True,False,True,False])

In [ ]:
result=np.where(cond,xarr,yarr) # True면x , False면y
result

array([100,   2, 300,   4])

In [ ]:
np.where(xarr>200,max(xarr),0) # xarr가 200보다 크면 제일 큰 xarr, 아니면 0

array([  0,   0, 400, 400])

In [ ]:
np.where(xarr%3==0,1,0) # xarr의 나머지가 0이면 1출력, 아니면 0 출력

array([0, 0, 1, 0])

- sort

In [ ]:
np.random.seed(42)
arr=np.random.randint(1,100,size=10) # 1~100까지의 정수 중에 10개를 뽑아주세요.
arr

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [ ]:
arr.sort() # sort는 원래값이 바뀐다.
arr

array([15, 21, 52, 61, 72, 75, 75, 83, 87, 93])

In [ ]:
-np.sort(-arr) # -를 넣어야 내림차순 정렬 가능

array([93, 87, 83, 75, 75, 72, 61, 52, 21, 15])

- array의 sort에서는 내림차순, 오름차순을 선택하는 옵션이 없음

In [ ]:
lst=[1,32,4,1,20]
lst.sort(reverse=True)
lst

[32, 20, 4, 1, 1]

- 선형대수 패키지
  - 단위 행렬
    - 대각선 원소 1이고, 나머지는 0인 n차 정방행렬을 말하며, numpy의 eye()함수를 사용하여서 만들 수 있음

In [ ]:
import numpy as np
identity=np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
identity=np.eye(2,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
identity=np.eye(5,5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


- 대각 행렬
  - 대각 성분 이외의 모든 성분이 모두 '0'인 n차 정방행렬

In [ ]:
x=np.arange(9).reshape(3,-1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
np.diag(x) # 대각선 값

array([0, 4, 8])

In [ ]:
np.diag(np.diag(x)) # 대각선값 빼고 0으로 바꿈

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

- dot
  - 벡터의 내적, 원소간의 곱(element-wise product)
  - 벡터의 내적(행렬의 곱)

In [ ]:
a=np.arange(4).reshape(-1,2)
print(a)

[[0 1]
 [2 3]]


In [ ]:
a*a # dot product

array([[0, 1],
       [4, 9]])

In [ ]:
np.multiply(a,a)

array([[0, 1],
       [4, 9]])

In [ ]:
np.dot(a,a) # 행렬의 곱

array([[ 2,  3],
       [ 6, 11]])

In [ ]:
a.dot(a)

array([[ 2,  3],
       [ 6, 11]])

- matmul:matrix multiplication

In [ ]:
a = np.random.randint(-3,3,10).reshape(2,5) # 범위 안의 난수 10개
b = np.random.randint(0,5,15).reshape(5,3) 
a.shape,b.shape

((2, 5), (5, 3))

In [ ]:
np.random.seed(2) #시드값을 2로 고정
arr = np.random.randint(1, 10, 10)
print(arr)

[9 9 7 3 9 8 3 2 6 5]


In [ ]:
ab = np.matmul(a,b)
print(ab.shape,'\n') #\n : 개행
print(ab)

(2, 3) 

[[-12  10   6]
 [-11 -38 -44]]


In [ ]:
ba=np.matmul(b,a) # 오류
ab=np.mutmul(a,b,T) # 오류

In [ ]:
np.dot(a,b)

array([[10,  9, 11],
       [ 4,  7,  3]])

- pandas
  - numpy를 배열 기반인 분석용 라이브러리
  - 결측치 측정에 유리
  - 벡터 = 시리즈(리스트+딕셔너리)

In [ ]:
import numpy as np
import pandas as pd
obj = pd.Series([0,1,2,3,4,5,6,7], index=['a','b','c','d','e','f','g','h'], dtype='int64')
obj

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

- integer-location based(정수로 접근)
  - 순서에 입각

In [ ]:
obj[3]

3

In [ ]:
obj[-1]

7

In [ ]:
obj[[1,3,5]] # multi index 접근방법

b    1
d    3
f    5
dtype: int64

In [ ]:
obj[1:3]

b    1
c    2
dtype: int64

In [ ]:
obj<3 # boolean indexing

a     True
b     True
c     True
d    False
e    False
f    False
g    False
h    False
dtype: bool

- label location based

In [ ]:
obj

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [ ]:
obj.c # c의 위치

2

In [ ]:
obj['c']

2

In [ ]:
obj[['e','c']]

e    4
c    2
dtype: int64

In [ ]:
obj['a':'d']

a    0
b    1
c    2
d    3
dtype: int64

In [ ]:
obj['d':'e']=100 # numpy의 브로드캐스팅
obj

a      0
b      1
c      2
d    100
e    100
f      5
g      6
h      7
dtype: int64

- integer location based(iloc)

In [ ]:
import numpy as np
import pandas as pd
obj = pd.Series([0,1,2,3,4,5,6,7], index=['a','b','c','d','e','f','g','h'], dtype='int64')
obj

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int64

In [ ]:
obj.iloc[2]

2

In [ ]:
obj.iloc[[2]] # 라벨, 값 

c    2
dtype: int64

In [ ]:
obj.iloc[1:4] # 슬라이싱

b    1
c    2
d    3
dtype: int64

- location based

In [ ]:
obj.loc['a':'c']

a    0
b    1
c    2
dtype: int64

- dataframe
  - 시리즈가 여러개 뭉쳐있는 것

In [ ]:
df=pd.DataFrame(np.arange(24).reshape(4,-1),
                columns=['c1','c2','c3','c4','c5','c6'],
                index=['r1','r2','r3','r4'])
df

c1  c2  c3  c4  c5  c6
r1   0   1   2   3   4   5
r2   6   7   8   9  10  11
r3  12  13  14  15  16  17
r4  18  19  20  21  22  23

In [ ]:
df['c3']

r1     2
r2     8
r3    14
r4    20
Name: c3, dtype: int32

In [ ]:
df.c3

r1     2
r2     8
r3    14
r4    20
Name: c3, dtype: int32

In [ ]:
df['c1','c3'] # 오류 1개 이상이면 다중인덱스로 접근해야 함

In [ ]:
df[['c1','c3']] # 멀티인덱스

c1  c3
r1   0   2
r2   6   8
r3  12  14
r4  18  20

In [ ]:
df['r1':'r2']

c1  c2  c3  c4  c5  c6
r1   0   1   2   3   4   5
r2   6   7   8   9  10  11

In [ ]:
df[['c1','c2']] # 열중심 역주행

c1  c2
r1   0   1
r2   6   7
r3  12  13
r4  18  19

- iloc

In [ ]:
df.iloc[[0],[3]]

c4
r1   3

In [ ]:
df.iloc[[0,1],1:4]

c2  c3  c4
r1   1   2   3
r2   7   8   9

In [ ]:
df.loc[['r1'],['c4']]

c4
r1   3

In [ ]:
df.loc['r1':'r2',['c2','c3','c4']]

c2  c3  c4
r1   1   2   3
r2   7   8   9

In [ ]:
df.loc['r1':'r2',['c3','c4','c2']]

c3  c4  c2
r1   2   3   1
r2   8   9   7

- 산술연산자

In [ ]:
s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
s2=pd.Series([10,20,30,40], index=['a','b','c','d'])
s1+s2

a    11
b    22
c    33
d    44
dtype: int64

In [ ]:
s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
s2=pd.Series([10,20,30,40], index=['b','c','d','e'])
s1+s2 # NaN(not a number) SQL의 outer join

a     NaN
b    12.0
c    23.0
d    34.0
e     NaN
dtype: float64

In [ ]:
s1.add(s2, fill_value=0) # 빈값은 0으로 채워주세요.

a     1.0
b    12.0
c    23.0
d    34.0
e    40.0
dtype: float64

In [ ]:
s2.add(s1, fill_value=0)

a     1.0
b    12.0
c    23.0
d    34.0
e    40.0
dtype: float64

In [ ]:
import pandas as pd
stock=pd.read_csv('https://raw.githubusercontent.com/Youngpyoryu/Lecture_Note/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC/stock_2020_01.csv', encoding='CP949')
stock

Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0    2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1    2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2    2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745
3    2020. 1. 7 오후 3:30:00  2175.54  663.44            11180       108400
4    2020. 1. 8 오후 3:30:00  2151.31  640.94            11360       108270
5    2020. 1. 9 오후 3:30:00  2186.45  666.09            11055       107980
6   2020. 1. 10 오후 3:30:00  2206.39  673.03            11035       107760
7   2020. 1. 13 오후 3:30:00  2229.26  679.22            11080       107695
8   2020. 1. 14 오후 3:30:00  2238.88  678.71            10975       107860
9   2020. 1. 15 오후 3:30:00  2230.98  679.16            11060       108020
10  2020. 1. 16 오후 3:30:00  2248.05  686.52            11060       108015
11  2020. 1. 17 오후 3:30:00  2250.57  688.41            11075       107830
12  2020. 1. 20 오후 3:30:00  2262.64  683.47            11140       107775
13  2020. 1. 21 오후 3:30:00  2239.69  676.52            11155       108040
14  2020. 1. 22 오후 3:30:00  2267.25  688.25            11050       107995
15  2020. 1. 23 오후 3:30:00  2246.13  685.57            11080       107970
16  2020. 1. 28 오후 3:30:00  2176.72  664.70            11250       108450
17  2020. 1. 29 오후 3:30:00  2185.28  670.18            11160       108585
18  2020. 1. 30 오후 3:30:00  2148.00  656.39            11225       108810
19  2020. 1. 31 오후 3:30:00  2119.01  642.48            11210       108795

In [ ]:
stock=pd.read_csv('C:/Users/405/my_study/Python_Study/0503/stock_2020_01.csv', encoding='CP949')
stock

Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0    2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1    2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2    2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745
3    2020. 1. 7 오후 3:30:00  2175.54  663.44            11180       108400
4    2020. 1. 8 오후 3:30:00  2151.31  640.94            11360       108270
5    2020. 1. 9 오후 3:30:00  2186.45  666.09            11055       107980
6   2020. 1. 10 오후 3:30:00  2206.39  673.03            11035       107760
7   2020. 1. 13 오후 3:30:00  2229.26  679.22            11080       107695
8   2020. 1. 14 오후 3:30:00  2238.88  678.71            10975       107860
9   2020. 1. 15 오후 3:30:00  2230.98  679.16            11060       108020
10  2020. 1. 16 오후 3:30:00  2248.05  686.52            11060       108015
11  2020. 1. 17 오후 3:30:00  2250.57  688.41            11075       107830
12  2020. 1. 20 오후 3:30:00  2262.64  683.47            11140       107775
13  2020. 1. 21 오후 3:30:00  2239.69  676.52            11155       108040
14  2020. 1. 22 오후 3:30:00  2267.25  688.25            11050       107995
15  2020. 1. 23 오후 3:30:00  2246.13  685.57            11080       107970
16  2020. 1. 28 오후 3:30:00  2176.72  664.70            11250       108450
17  2020. 1. 29 오후 3:30:00  2185.28  670.18            11160       108585
18  2020. 1. 30 오후 3:30:00  2148.00  656.39            11225       108810
19  2020. 1. 31 오후 3:30:00  2119.01  642.48            11210       108795

In [ ]:
stock.head(3) #위에서 5개

Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0  2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1  2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2  2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745

In [ ]:
stock.tail()

Date    kospi  kosdaq  gold_fut_132030  Bond_273130
15  2020. 1. 23 오후 3:30:00  2246.13  685.57            11080       107970
16  2020. 1. 28 오후 3:30:00  2176.72  664.70            11250       108450
17  2020. 1. 29 오후 3:30:00  2185.28  670.18            11160       108585
18  2020. 1. 30 오후 3:30:00  2148.00  656.39            11225       108810
19  2020. 1. 31 오후 3:30:00  2119.01  642.48            11210       108795

In [ ]:
stock.describe() # 중앙값 median= 50%

kospi      kosdaq  gold_fut_132030  Bond_273130
count    20.00000   20.000000        20.000000      20.0000
mean   2203.44250  671.117000     11112.000000  108188.7500
std      43.83648   14.040831       115.762916     364.6912
min    2119.01000  640.940000     10845.000000  107695.0000
25%    2175.44750  664.385000     11053.750000  107942.5000
50%    2196.42000  673.525000     11080.000000  108030.0000
75%    2241.30000  680.282500     11187.500000  108478.7500
max    2267.25000  688.410000     11360.000000  108810.0000

In [11]:
import numpy as np
A = np.array([16,12,28,8,18,17,28,24,5,4,12,16,8,4,4,4])

In [12]:
sorted(A)

[4, 4, 4, 4, 5, 8, 8, 12, 12, 16, 16, 17, 18, 24, 28, 28]

In [13]:
np.mean(A)

13.0

In [14]:
np.median(A)

12.0

- 결측치

In [15]:
stock.isna().sum()
#stock.isnull().sum()

Date               0
kospi              0
kosdaq             0
gold_fut_132030    0
Bond_273130        0
dtype: int64

- 데이터의 자료형 ->info()

In [16]:
stock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Date             20 non-null     object 
 1   kospi            20 non-null     float64
 2   kosdaq           20 non-null     float64
 3   gold_fut_132030  20 non-null     int64  
 4   Bond_273130      20 non-null     int64  
dtypes: float64(2), int64(2), object(1)
memory usage: 928.0+ bytes


In [17]:
stock['Date']

0      2020. 1. 2 오후 3:30:00
1      2020. 1. 3 오후 3:30:00
2      2020. 1. 6 오후 3:30:00
3      2020. 1. 7 오후 3:30:00
4      2020. 1. 8 오후 3:30:00
5      2020. 1. 9 오후 3:30:00
6     2020. 1. 10 오후 3:30:00
7     2020. 1. 13 오후 3:30:00
8     2020. 1. 14 오후 3:30:00
9     2020. 1. 15 오후 3:30:00
10    2020. 1. 16 오후 3:30:00
11    2020. 1. 17 오후 3:30:00
12    2020. 1. 20 오후 3:30:00
13    2020. 1. 21 오후 3:30:00
14    2020. 1. 22 오후 3:30:00
15    2020. 1. 23 오후 3:30:00
16    2020. 1. 28 오후 3:30:00
17    2020. 1. 29 오후 3:30:00
18    2020. 1. 30 오후 3:30:00
19    2020. 1. 31 오후 3:30:00
Name: Date, dtype: object

In [18]:
stock['kospi'].sort_values()

19    2119.01
18    2148.00
4     2151.31
2     2155.07
0     2175.17
3     2175.54
1     2176.46
16    2176.72
17    2185.28
5     2186.45
6     2206.39
7     2229.26
9     2230.98
8     2238.88
13    2239.69
15    2246.13
10    2248.05
11    2250.57
12    2262.64
14    2267.25
Name: kospi, dtype: float64

In [20]:
stock.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [21]:
stock['kospi'].unique() #Series

array([2175.17, 2176.46, 2155.07, 2175.54, 2151.31, 2186.45, 2206.39,
       2229.26, 2238.88, 2230.98, 2248.05, 2250.57, 2262.64, 2239.69,
       2267.25, 2246.13, 2176.72, 2185.28, 2148.  , 2119.01])

- unique
    - 중복되는 값을 제거하고 유일한 값만 담고 있는 Series를 반환.


In [22]:
obj = pd.Series([2,1,3,3,1,5,np.nan,1,2])
obj

0    2.0
1    1.0
2    3.0
3    3.0
4    1.0
5    5.0
6    NaN
7    1.0
8    2.0
dtype: float64

In [24]:
obj.isnull().sum()

1

In [25]:
obj.unique() #Series밖에 안됨 DataFrame에는 안됨.

array([ 2.,  1.,  3.,  5., nan])

- value_counts

In [26]:
obj.value_counts()

1.0    3
2.0    2
3.0    2
5.0    1
Name: count, dtype: int64

In [28]:
obj.value_counts(normalize=True)

1.0    0.375
2.0    0.250
3.0    0.250
5.0    0.125
Name: proportion, dtype: float64

In [29]:
obj.sort_values()

1    1.0
4    1.0
7    1.0
0    2.0
8    2.0
2    3.0
3    3.0
5    5.0
6    NaN
dtype: float64

In [30]:
obj = pd.Series([1,2,3,-1,-2], index=list('가마나라다'))
obj

가    1
마    2
나    3
라   -1
다   -2
dtype: int64

In [31]:
obj.sort_index(ascending=False)

마    2
라   -1
다   -2
나    3
가    1
dtype: int64

In [32]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),
                     index = list('abc'),
                     columns = list('edf'))
frame

e  d  f
a  0  1  2
b  3  4  5
c  6  7  8

In [33]:
frame.sort_index()

e  d  f
a  0  1  2
b  3  4  5
c  6  7  8

In [34]:
frame.sort_index(axis=1)

d  e  f
a  1  0  2
b  4  3  5
c  7  6  8

In [35]:
frame

e  d  f
a  0  1  2
b  3  4  5
c  6  7  8

In [36]:
frame.sort_values(by='e',ascending=False)

e  d  f
c  6  7  8
b  3  4  5
a  0  1  2

In [37]:
frame.sort_values(by=['e','f'],ascending=[False,True])

e  d  f
c  6  7  8
b  3  4  5
a  0  1  2

- map
    - Series의 각각의 element들을 다른 어떤 값을 대체하는 역할.

In [38]:
series = pd.Series([100,200,300])
series

0    100
1    200
2    300
dtype: int64

In [39]:
series.map({100:'C',200:'B',300:'A'})

0    C
1    B
2    A
dtype: object

In [40]:
series.map('${}'.format)

0    $100
1    $200
2    $300
dtype: object

In [41]:
series.map('{}달러'.format)

0    100달러
1    200달러
2    300달러
dtype: object

In [42]:
f = lambda x: np.add(x,3)
series.map(f)

0    103
1    203
2    303
dtype: int32

- apply
    - map보다 적용할 수 있는 범위가 큰 것.

In [43]:
s = pd.Series([20,21,12], index=['London','New York','Helsinki'])
s

London      20
New York    21
Helsinki    12
dtype: int64

In [44]:
def sub_custom_value(x,val):
    return x-val

In [45]:
s.apply(sub_custom_value,args=(10,))

London      10
New York    11
Helsinki     2
dtype: int64

In [46]:
def add_custom_values(x,**kwargs):
    for month in kwargs:
        x +=kwargs[month]
    return x

In [47]:
s.apply(add_custom_values, june=30, july=20,august=25)

London      95
New York    96
Helsinki    87
dtype: int64